stages:
  - test
  - publish

default:
  tags:
    - infra-cicd

test-job:
  image: node:16.14.2
  stage: test
  cache:
    key: npm
    policy: pull-push
    paths:
      - .npm/
  script:
    - npm ci
    - npm run test
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - lib/
    expire_in: 1 days

publish-job:
  image: node:16.14.2
  stage: publish
  only:
    - /^release\/*/
  cache:
    key: npm
    policy: pull-push
    paths:
      - .npm/
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}">.npmrc
    - npm publish

